### ISSUE TITLE
Code only has 2 spaces

### ISSUE THREAD

**Issue by pjo336** [alexbaumhoer/go-hello-spaces#1]
GoLang should have 8 spaces, clearly

**Comment by pjo336** [comment]
+1

**Comment by pjo336** [comment]
Any update on this issue? My team needs this feature

**Comment by alexbaumhoer** [comment]
@pjo336 we are waiting for Go to support generics before making any updates here

**Comment by pjo336** [comment]
Hi, I see you have great experience with go. Wondering if you would like a job in Trenton New Jersey for 20k/yr. no remote allowed. Please send an updated resume
